root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp\\main.exe ."
  bin = "tmp\\main.exe"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test.go"]
  stop_on_error = true
  shell = "C:\\Windows\\System32\\cmd.exe /C"
  send_interrupt = false
  kill_delay = "0s"

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
